# Site settings
title: Frank's blog - Developer, coffee lover and traveler
description: iOS development sharing, Swift, Objective-C
author: Frank(wchuang)
github: https://github.com/wchuang
about: I'm Frank, an Sr. iOS Engineer, an ex-DiDier from Taiwan.
disqus_shortname: wchuang
#google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/weicccc"
    - icon: fa-twitter
      link: "https://twitter.com/huang_wc"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/franklol/"
    - icon: fa-github
      link: "https://github.com/wchuang"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
#    - text: My Projects
#      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://blog.wchuang.cc/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
#encoding: UTF-8
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
